exec 'source' g:modulesRoot . 'plugins.vim'
" exec 'source' g:modulesRoot . 'plugins-syntastic.vim'
exec 'source' g:modulesRoot . 'plugins-airline.vim'
exec 'source' g:modulesRoot . 'plugins-coc.vim'
exec 'source' g:modulesRoot . 'plugins-ale.vim'
exec 'source' g:modulesRoot . 'plugins-vim-javascript.vim'
exec 'source' g:modulesRoot . 'plugins-gitgutter.vim'
exec 'source' g:modulesRoot . 'gui.vim'
exec 'source' g:modulesRoot . 'common.vim'
